version: "3.1"

services:
  influxdb:
    restart: always
    image: influxdb:1.5.4-alpine
    hostname: influxdb_service
    ports:
      - "8086:8086"
    volumes:
       - ./influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      default:
        ipv4_address: 172.18.1.4
        aliases:
          - redis.service
networks:
    default:
        external:
            name: default
