version: "3.1"

services:
  influxdb:
    restart: always
    image: influxdb:1.5.4-alpine
    hostname: influxdb_service
    ports:
      - "8086:8086"
    volumes:
       - ./influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      default:
        ipv4_address: 172.18.1.4
        aliases:
          - redis.service

    alerts:
      restart: always
      image: chariot_fog_storage_alerts
      hostname: chariot_fog_storage_alerts
      networks:
        default:
          ipv4_address: 172.18.1.5
          aliases:
            - alerts.service

    logs:
      restart: always
      image: chariot_fog_storage_logs
      hostname: chariot_fog_storage_logs
      networks:
        default:
          ipv4_address: 172.18.1.6
          aliases:
            - logs.service
networks:
    default:
        external:
            name: deploy_default
